<?php
defined("BASEPATH") OR exit("No direct script access allowed");
$config["sitename"] = 'LINDA IKEJI TV';
$config["logo"] = '<img src="http://192.168.64.2/litv2/uploads/images/default/LITV%20LOGO%20WHITE.png" alt="LINDA IKEJI TV" >';
$config["theme"] = 'darktheme';
$config["emailsite"] = "support@lindaikejitv.com";
$config["freeWebsite"] = FALSE;
$config["comments_moderation"] = TRUE;
$config["confirmation_inscription"] = FALSE;
$config["maintenance"] = FALSE;
$config["maintenance_message"] = "Maintenance message";
$config["facebook"] = "https://www.facebook.com/lindaikejitv";
$config["twitter"] = "https://twitter.com/lindaikejitv";
$config["google"] = "https://plus.google.com/b/113675398586774502189/113675398586774502189";
$config["terms"] = "privacy-policy";
$config["facebookPageName"] = "Linda Ikeji TV";
$config["facebookPageLink"] = "https://www.facebook.com/lindaikejitv";
$config["clientId"] = "891249173125-bcgnpsn0vbgbs8q53uoi61jg2ua3qkf9.apps.googleusercontent.com";
$config["clientSecret"] = "1bEeg6TUMPfhcJK7_EGDHtmL";
$config["facebook_app_id"] = "1349165995196959";
$config["facebook_app_secret"] = "52febcccd75f4f1e757ae4d3d6de1f24";
$config["consumerKey"] = "";
$config["consumerSecret"] = "";
$config["mailchimpApi"] = 'fa11ec31dc35fa13d03664cd62c9790b-us9';
$config["mailchimpList"] = '0e1f1fba62';
$config["amazonApiKey"] = 'AKIAIE5KL3EJBBDYFQZA';
$config["amazonSecretKey"] = '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';
$config["amazonRegion"] = 'us-east-1';
$config["amazonBucket"] = 'nouveaubucket';
$config["amazonCloudFront"] = 'd3pg7aw67nmiqp.cloudfront.net';
$config["amazonBrowserUpload"] = '1';
$config["hidePromo"] = FALSE;
?>